Conferences: Section of 'Personnel'
music-encoding/music-encoding.github.io pull request #176
Opened 2020-11-14 05:21 UTC by martha-thomae

Here is the section of 'personnel' for each conference. The section now includes the local organizing committee, the program committee, and the keynotes. I changed its naming now that keynotes are included here too.

All the information about the staff involved is in the header of the file and it is loaded into the body using the template `_layouts/people.html`

I tried to make each entry consistent, always following the structure:
- name
- chair (optional)
- institutions
- country

This looks odd in two entries: "RISM Switzerland, Switzerland" and "National Library of Norway, Norway" (but only for those two).

One remaining inconsistency would be that in some years, there is no indication about who is the chair in a given committee (this is true for the oldest conferences). And another is the ordering of the names, in some years the order seems to be random, but with the chairs always at the beginning; in other years, all entries are ordered alphabetically. Any preferences to fix this?

2020-11-14 11:02 UTC, musicEnfanthen commented
Thanks @martha-thomae , looks great.

At least for "RISM Switzerland, Switzerland", you could go for "RISM CH, Switzerland", I guess (@lpugin ?)
@margrethesb Are you ok with "National Library of Norway, Norway"?

Would it make sense to have the file names, permalinks and layout to say "personnel" instead of "people", too?

Ad chairs: The only ones without chairs I can see are the OC's 2013 and 2014. I guess that's because everyone named there was co-chair at that time? (@kepper )

2020-12-09 11:59 UTC, musicEnfanthen requested changes
Thanks @martha-thomae . Since no one else responded, I'd suggest the following to go on with this PR:

Order of entries: Choose one order system (alphabetically with chairs included, OR alphabetically with chairs on top) and use it for all years. I'd prefer all alphabetical style, but the chairs on top version is sometimes easier to read. I'll leave that decision to you.

For years when there is no chair, there is none, that's fine.

Organization, Country: "National Library of Norway, Norway" should be fine. The first one is the name of the organization, the second one the country. Same for RISM, although we could change to "RISM CH, Switzerland", here.

Looking at the naming again, we should make it consistent, too. So when we stick with  "people", the ids should also be "people". Thus only the title will be "Personnel". (I have been thinking about "roles and responsibilities" lately, , but let's leave this for another PR).

Does the `people.html` show up properly for each year on your branch? Can't test it here.

2020-12-09 11:59 UTC, musicEnfanthen commented on _layouts/people.html
> +        <li><span style="font-weight: 400;">{{ omember }}</span></li>
I am not sure that `<span style="font-weight: 400;">` is necessary. Does it change anything when you remove it? (see also below)

2020-12-09 11:59 UTC, musicEnfanthen commented on _layouts/people.html
> +        <li><span style="font-weight: 400;">{{ pmember }}</span></li>
see above

2020-12-09 11:59 UTC, musicEnfanthen commented on _layouts/people.html
> +        <li><span style="font-weight: 400;">{{ speaker }}</span></li>
see above

2020-12-09 11:59 UTC, musicEnfanthen commented on _layouts/people.html
> +    <h2>Local Organizing Committee</h4>
```suggestion
    <h2>Local Organizing Committee</h2>
```
Should be h2 or h4

2020-12-09 11:59 UTC, musicEnfanthen commented on _layouts/people.html
> +    <h2>Program Committee</h4>
```suggestion
    <h2>Program Committee</h2>
```

2020-12-09 11:59 UTC, musicEnfanthen commented on _layouts/people.html
> +    <h2>Keynote Speakers</h4>
```suggestion
    <h2>Keynote Speakers</h2>
```

2020-12-09 11:59 UTC, musicEnfanthen commented on _layouts/people.html
> +<div style="margin-top:2em;">
```suggestion
<div class="columns">
  <div class="column col-10 col-sm-12">
```
Could you please try this, for responsive design. Will need an additional closing `</div>` at the end.

2020-12-09 11:59 UTC, musicEnfanthen commented on _conferences/2020/people.html
> +    - "David Weigl, University of Music and Performing Arts Vienna, Austria"
```suggestion
    - "David M. Weigl, University of Music and Performing Arts Vienna, Austria"
```
Sort by M.

2020-12-09 11:59 UTC, musicEnfanthen commented on _conferences/2019/people.html
> +    - "Johanne Devaney, Brooklyn College, CUNY, USA"
```suggestion
    - "Johanna Devaney, Brooklyn College, CUNY, USA"
```

2020-12-09 11:59 UTC, musicEnfanthen commented on _conferences/2020/people.html
> +    - "Anna Kijas (Committee Chair), Head, Lilly Music Library, Tufts University, USA"
```suggestion
    - "Anna E. Kijas (Committee Chair), Head, Lilly Music Library, Tufts University, USA"
```

2020-12-09 11:59 UTC, musicEnfanthen commented on _conferences/2018/people.html
> +    - "Anna Kijas, Boston College, USA"
```suggestion
    - "Anna E. Kijas, Boston College, USA"
```

2020-12-09 11:59 UTC, musicEnfanthen commented on _conferences/2018/people.html
> +    - "David Fiala, Centre d’études supérieures de la Renaissance, Université de Tours, France"
```suggestion
    - "David Fiala, Centre d’Études Supérieures de la Renaissance, Université de Tours, France"
```

2020-12-09 11:59 UTC, musicEnfanthen commented on _conferences/2017/people.html
> +    - "Philippe Vendrix (Committee Co-Chair), Centre d’études supérieures de la Renaissance (CESR), Université de Tours, France"
```suggestion
    - "Philippe Vendrix (Committee Co-Chair), Centre d’Études Supérieures de la Renaissance (CESR), Université de Tours, France"
```

2020-12-09 11:59 UTC, musicEnfanthen commented on _conferences/2017/people.html
> +    - "Philippe Rigaux (Committee Co-Chair), Conservatoire national des arts et métiers (CNAM), France"
```suggestion
    - "Philippe Rigaux (Committee Co-Chair), Conservatoire National des Arts et Métiers (CNAM), France"
```

2020-12-09 12:03 UTC, bwbohl commented
@musicEnfanthen thanks for pushing this forward and your great remarks, and @martha-thomae of course thanks for the initial impetus!
I think you both are n top of this and can decide how you see best!

2020-12-09 14:58 UTC, martha-thomae commented
Thanks, @musicEnfanthen. I will move on with your changes. Thanks for the reminder, @bwbohl.

2020-12-09 15:39 UTC, musicEnfanthen commented on _layouts/people.html
> +layout: default
```suggestion
layout: conference
```
This should be `conference`, to keep the side bar menu displayed.

2020-12-30 23:09 UTC, martha-thomae commented
@musicEnfanthen, thanks for all the suggestions, everything should be fine now!
And thanks for the patience, the last months of this year have been a bit hard for personal reasons. But now back to normality.

> Does the `people.html` show up properly for each year on your branch? Can't test it here.

Yes, all of them do show :)

2020-12-31 11:29 UTC, musicEnfanthen approved these changes

2020-12-31 11:29 UTC, merged

2020-12-31 11:29 UTC, musicEnfanthen commented
Thanks @martha-thomae for your work, looks great!