Filter uipcoming conference from past conferences overview
music-encoding/music-encoding.github.io pull request #179
Opened 2020-11-14 12:49 UTC by musicEnfanthen

This PR adds a filter to the `past.md` template to show only events that have a past `date-end` in their header, removing future events. 

It follows the approach described here: https://maedi.com/code/filter-by-date/

Fixes #178

2020-12-01 11:48 UTC, musicEnfanthen commented
@bwbohl Could you have a look?

2020-12-08 21:36 UTC, bwbohl requested changes
Good work! But somehow the order of the conferences get a bit twirked, i.e. MEC2013 is moved to the first position while all others remain anti-chronological

2020-12-09 13:11 UTC, musicEnfanthen commented
Thanks for looking at that @bwbohl . 

However, I can't reproduce your issue. When I run it locally, all the conferences are sorted chronologically:

![conf](https://user-images.githubusercontent.com/21059419/101634002-5e4adf00-3a28-11eb-9a2b-adb34c5aa0fa.PNG)

Where do you get the twirked order?

2020-12-09 13:37 UTC, bwbohl commented
however it happened when I ran it locally… let try this and see what happen online, agree?

2020-12-09 13:40 UTC, musicEnfanthen commented
Yes, agree :)

2020-12-09 13:41 UTC, musicEnfanthen commented
(PS: How do you run a PR locally? Is there anywhere a good explanation how to checkout a PR to test it?)

2020-12-09 14:55 UTC, bwbohl commented
I use the GitHub Desktop App for this

2020-12-09 15:44 UTC, musicEnfanthen commented
(OK, thanks, found also a way without GH Desktop App: https://stackoverflow.com/a/30584951)

2020-12-09 15:45 UTC, musicEnfanthen commented
Feel free to merge this PR whenever you want

2020-12-09 21:41 UTC, bwbohl approved these changes

2020-12-09 21:50 UTC, merged

2020-12-10 10:22 UTC, musicEnfanthen commented
Thank you. :) Order is correct in my browser, for you, too?

2020-12-11 08:25 UTC, bwbohl commented
yes correct here ;-) thanks for implementing!

2020-12-11 10:35 UTC, musicEnfanthen commented
Perfect, thanks.