Create CONTRIBUTING.md
music-encoding/music-encoding.github.io pull request #196
Opened 2020-12-08 21:18 UTC by bwbohl

copy and adapt from https://github.com/music-encoding/guidelines/blob/26990abf3523842592662cc949c2406f43d2dcdf/README.md

2020-12-11 08:22 UTC, bwbohl commented
Since the source code of the guidelines were merged back into this repository and the https://github.com/music-encoding/guidelines repo has been reconfigured to only hold automatically generated HTML pages of the guidelines the contribution guidlines there is no longer needed. As this repo was is pointing to a contribution guideline in the guidelines repo it was best moved here, because contribution now happens here, for both schemata and guidelines.

2021-01-19 15:59 UTC, bwbohl commented
@ahankinson @kepper @musicEnfanthen any concerns merging?

2021-01-19 16:12 UTC, ahankinson approved these changes
I'm assuming that all the directions are still correct, so no issues from me.

2021-01-19 17:07 UTC, musicEnfanthen requested changes

2021-01-19 17:07 UTC, musicEnfanthen commented on CONTRIBUTING.md
> +If you wish to contribute changes to the MEI website, you can edit the files directly on GitHub. The text of the Guidelines is written in a dialect of [Markdown](https://kramdown.gettalong.org/quickr
Last sentence needs to be adapted, or isn't it needed at all?

2021-01-19 17:08 UTC, musicEnfanthen commented
Thanks for the reminder! Small change request above.

2021-01-19 22:16 UTC, musicEnfanthen approved these changes

2021-01-19 22:18 UTC, musicEnfanthen commented
Looks good. Thanks for getting this helpful information back in.

2021-01-19 22:18 UTC, merged