created code of conduct
music-encoding/music-encoding.github.io pull request #416
Opened 2022-11-30 22:41 UTC by annakijas1

Created code of conduct page under "Community." Need to add to page to the menu under "Community"

2022-11-30 23:20 UTC, bwbohl requested changes
the two comments and suggestions I made also apply to all other headings and lists.

2022-11-30 23:20 UTC, bwbohl commented on community/code-of-conduct.md
> +## **1. Purpose**
here and at all other headings the asterisks for marking text bold are not needed, as the styles of the page will automatically render them bold.

```suggestion
## 1. Purpose
```

2022-11-30 23:20 UTC, bwbohl commented on community/code-of-conduct.md
> +* Remember that community event venues may be shared with members of the public; please be respectful to all patrons of these locations.
The empty lines between the list bullets are not needed.  The resulting HTML list is valid. Nevertheless, the list entries will each be wrapped in an HTML paragraph element which will take up more space. If that is your intention, it is fine with me, but usually, we have more compact lists on the website (accomplished by leaving away the additional line break).

```suggestion
* Participate in an authentic and active way. In doing so, you contribute to the health and longevity of this community.
* Exercise consideration and respect in your speech and actions.
* Attempt collaboration before conflict.
* Refrain from demeaning, discriminatory, or harassing behavior and speech.
* Be mindful of your surroundings and of your fellow participants. Alert community leaders if you notice a dangerous situation, someone in distress, or violations of this Code of Conduct, even if they seem inconsequential.
* Remember that community event venues may be shared with members of the public; please be respectful to all patrons of these locations.
```

You can compare the result in the following example:

* this is a list with

* paragraphs

* caused by the additional line-breaks

vs.

* a more
* compact list
* without additional empty lines

2022-11-30 23:25 UTC, bwbohl commented
Adding the page to the submenu can be done by adding it in the [_config.yml](https://github.com/music-encoding/music-encoding.github.io/blob/33d51ee125a72ca33d334d4f2c1a00ac8b205b93/_config.yml) of your branch.

The submenu of the conference menu entry is located at:
https://github.com/music-encoding/music-encoding.github.io/blob/33d51ee125a72ca33d334d4f2c1a00ac8b205b93/_config.yml#L23-L44

2022-12-01 13:28 UTC, musicEnfanthen requested changes

2022-12-01 13:28 UTC, musicEnfanthen commented on community/code-of-conduct.md
> +The Music Encoding Initiative Community Code of Conduct is based on the [Citizen Code of Conduct](https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md) distributed by[ ](http:/
```suggestion
The Music Encoding Initiative Community Code of Conduct is based on the [Citizen Code of Conduct](https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md) distributed by [Stumptown Syndicate](http://stumptownsyndicate.org) under a [Creative Commons Attribution-ShareAlike license](http://creativecommons.org/licenses/by-sa/3.0/). Portions of text derived from the [Django Code of Conduct](https://www.djangoproject.com/conduct/) and the [Geek Feminism Anti-Harassment Policy](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy).
```

2022-12-01 17:04 UTC, musicEnfanthen approved these changes

2022-12-01 17:17 UTC, musicEnfanthen commented
@annakijas1 @bwbohl I added the code-of-conduct page to the config.yml and also the Jekyll frontend at beginning of the code's page directly to this branch, so the page should be displayed when published (checked locally). Please have a look.

2022-12-07 20:42 UTC, musicEnfanthen commented
@bwbohl Are you fine with the changes?

2022-12-08 07:45 UTC, merged