Update mei-board members for 2023
music-encoding/music-encoding.github.io pull request #422
Opened 2022-12-19 09:45 UTC by bwbohl

This is still a draft, especially as @annplaksin and @musicog still should review their affiliations, AND of course it should only be merged after 2022

2022-12-19 09:52 UTC, musicog requested changes
Very exciting! :-)

Two small modification requests: Please flip the Institut in front of the Universität, and please add "mdw –" before the Universität (...branding reasons...), like so:

> **David M. Weigl**, Institut für musikalische Akustik – Wiener Klangstil, mdw – Universität für Musik und darstellende Kunst Wien

Thanks!

2022-12-19 10:23 UTC, annplaksin approved these changes
So exciting!
I'm fine, with the changes

2022-12-19 16:10 UTC, rettinghaus approved these changes

2022-12-19 16:20 UTC, musicog approved these changes
Perfect, thanks!

2023-01-03 17:14 UTC, rettinghaus commented
@musicEnfanthen please merge if appropriate.

2023-01-03 19:25 UTC, musicEnfanthen commented on community/mei-board.md
> +* **Perry Roland**, University of Virginia Library, Charlottesville (2015–2018, 2020–2022)
If I remember correctly, we used alphabetical order for previous Board members. @bwbohl Can you please sort accordingly?

2023-01-09 09:44 UTC, rettinghaus approved these changes

2023-01-09 09:53 UTC, musicEnfanthen approved these changes
Thank you

2023-01-09 09:53 UTC, merged