Mec2024
music-encoding/music-encoding.github.io pull request #600
Opened 2024-04-10 19:45 UTC by annakijas1

updated image banner

2024-04-11 07:39 UTC, rettinghaus requested changes
Thank you. One small request.

2024-04-13 09:40 UTC, musicEnfanthen commented on _conferences/2024/accommodation.html
> +<img src="/images/conference/2024/MEC_F24_Web-Banner-Updated-Dates.png" class="img-responsive" alt="Music Encoding Conference, University of North Texas, Denton, TX, 20-23nd May 2024" style="margin-b
Fixed.

2024-04-13 09:41 UTC, musicEnfanthen commented
The new banner is gorgeous, thank you (@annakijas1  @mfeustle ).

2024-04-13 16:30 UTC, rettinghaus approved these changes

2024-04-13 16:30 UTC, merged