fix(tutorials): fix incipit tutorial
music-encoding/music-encoding.github.io pull request #645
Opened 2024-05-20 19:42 UTC by musicEnfanthen

This PR adds some improvements for the incipt tutorial, including those proposed in #263 by @mfeustle .

This includes : 
- simplifying the note example in step 4;
- simplifying and improving readability of the xml:ids used in the final step;
- improving the explanation of the attributes used in the final step;
- improving the explanation of the referencing mechanism with xml:ids in the final step;
- fixing a typo in the title of the incipit tutorial in the Spanish translation.

Fixes #263

2024-05-20 19:43 UTC, musicEnfanthen commented
@martha-thomae May I ask you to have a look at the updated Spanish translations?

2024-07-30 07:14 UTC, rettinghaus commented
@martha-thomae Could you have a look please?

2025-01-08 08:25 UTC, bwbohl commented
pinging reviewers

2025-01-08 18:58 UTC, martha-thomae commented
Thanks, Benni, Klaus, and Stefan, I will look at this during this week to get it done :)

2025-01-12 03:01 UTC, martha-thomae reviewed
A few minor corrections for the writing in Spanish. And one extra paragraph that was missing in the Spanish translation of the English version. Thanks for all your work, @musicEnfanthen!

One small question (@musicEnfanthen, @rettinghaus, @bwbohl), do you remember how could I check from my own fork a branch of another person? Like this branch from Stefan, how can I see it on my fork to be able to run the website and see the changes locally? and also be able to actually make commits here? Thank you!

2025-01-13 21:25 UTC, bwbohl commented
> A few minor corrections for the writing in Spanish. And one extra paragraph that was missing in the Spanish translation of the English version. Thanks for all your work, @musicEnfanthen!
> 
> One small question (@musicEnfanthen, @rettinghaus, @bwbohl), do you remember how could I check from my own fork a branch of another person? Like this branch from Stefan, how can I see it on my fork to be able to run the website and see the changes locally? and also be able to actually make commits here? Thank you!

@martha-thomae In your above comments you can click the document with-+and- to add a suggestion for the marked lines and add your changes there. Theses then can be committed directly.

I’ll make one example for the deletion of 'del legado' above (https://github.com/music-encoding/music-encoding.github.io/pull/645#discussion_r1912351606)

2025-01-13 21:25 UTC, bwbohl commented on _tutorials-ES/102_incipit/step-12/102_incipit_step-12-desc.html
> +        Estos deben ser valores únicos para cada <code>@xml:id</code>, por lo que para este ejemplo usamos los valores: <code>"d4567"</code> para el <code>xml:id</code> de la nota inicial y <code>"d4
```suggestion
        Estos deben ser valores únicos para cada <code>@xml:id</code>, por lo que para este ejemplo usamos los valores: <code>"d4567"</code> para el <code>xml:id</code> de la nota inicial y <code>"d4568"</code> para el <code>xml:id</code> de la nota final. 
```

2025-01-16 15:08 UTC, musicEnfanthen commented
@martha-thomae Thanks for your review. 

You can checkout any branch very easily by using gh cli tools: https://cli.github.com/ . You can then build the branch locally (see [CONTRIBUTING.md](https://github.com/music-encoding/music-encoding.github.io/blob/main/CONTRIBUTING.md) for manual how to do that).

To propose changes to this PR, as @bwbohl explained, you can click on the "Files changed" tab at the top of this PR and then click on the +/- signs at the beginning of a changed line.

2025-01-17 02:39 UTC, martha-thomae requested changes
Thanks @bwbohl and @musicEnfanthen for the help! I added now the actual changes :) thank you!

2025-01-17 02:39 UTC, martha-thomae commented on _tutorials-ES/102_incipit/step-12/102_incipit_step-12-desc.html
> +
```suggestion
<p>En el caso de una ligadura <code>&lt;slur&gt;</code>, el atributo <code>@startid</code> hace referencia al <code>@xml:id</code> del elemento donde la ligadura inicia y el atributo <code>@endid</code> hace referencia al <code>@xml:id</code> del elemento donde la ligadura termina.</p>
```

2025-01-17 02:39 UTC, martha-thomae commented on _tutorials-ES/102_incipit/step-12/102_incipit_step-12-desc.html
> +    <p>Debido a que los ligaduras pueden estar curvados en diferentes direcciones, el atributo <code>@curvedir</code> describe una curva con un término genérico que indica la dirección de la curvatur
```suggestion
    <p>Debido a que las ligaduras pueden estar curvadas en diferentes direcciones, el atributo <code>@curvedir</code> describe una curva con un término genérico que indica la dirección de la curvatura de la ligadura: <code>“above”</code>, <code>“below”</code> o <code>“mixed”</code>.</p>
```

2025-01-17 02:39 UTC, martha-thomae commented on _tutorials-ES/102_incipit/step-12/102_incipit_step-12-desc.html
> +    <p class="tutorialTask">Identifica la primera y la última nota a la que se une la ligadura (dentro del primer elemento <code>&lt;beam&gt;</code> del compás 3) y añade <code>@xml:id</code>s a ambo
```suggestion
    <p class="tutorialTask">Identifica la primera y la última nota que forman parte de la ligadura (dentro del primer elemento <code>&lt;beam&gt;</code> del compás 3) y añade <code>@xml:id</code>s a ambos elementos <code>&lt;note&gt;</code>. 
```

2025-01-17 02:42 UTC, martha-thomae approved these changes
I think this can be merged now :)

2025-01-17 10:08 UTC, musicEnfanthen commented on _tutorials-ES/102_incipit/step-12/102_incipit_step-12-desc.html
> +    <p>En este último paso, se utilizará el segundo enfoque: Al igual que las dinámicas, los elementos <code>&lt;slur&gt;</code> (lidaduras) son <i>eventos de control</i>. No se codifican como elemen
@martha-thomae correct? or ligaduras?

2025-01-17 16:55 UTC, martha-thomae commented on _tutorials-ES/102_incipit/step-12/102_incipit_step-12-desc.html
> +    <p>En este último paso, se utilizará el segundo enfoque: Al igual que las dinámicas, los elementos <code>&lt;slur&gt;</code> (lidaduras) son <i>eventos de control</i>. No se codifican como elemen
Sorry, my bad!

2025-01-17 16:57 UTC, martha-thomae approved these changes

2025-01-17 16:57 UTC, martha-thomae commented on _tutorials-ES/102_incipit/step-12/102_incipit_step-12-desc.html
> +    <p>En este último paso, se utilizará el segundo enfoque: Al igual que las dinámicas, los elementos <code>&lt;slur&gt;</code> (lidaduras) son <i>eventos de control</i>. No se codifican como elemen
```suggestion
    <p>En este último paso, se utilizará el segundo enfoque: Al igual que las dinámicas, los elementos <code>&lt;slur&gt;</code> (ligaduras) son <i>eventos de control</i>. No se codifican como elementos hijos de los eventos correspondientes que deben controlar, sino que se colocan en la mayoría de los casos fuera de los elementos <code>staff</code>.
```

2026-01-31 14:36 UTC, merged